eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  #自定义eureka 客户端连接,访问客户端的时候显示名称
  instance:
    instance-id: eureka-client
spring:
  application:
    name: eureka-client
  cloud:
    config:
      discovery:
        enable: true
        server-id: config-server
      profile: dev
server:
  port: 7080
